import 'package:flutter/material.dart';

// Light and dark ColorSchemes made by FlexColorScheme v7.3.1.
// These ColorScheme objects require Flutter 3.7 or later.\
class AppColors {
  static const ColorScheme flexSchemeLight = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff1460a5),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffd3e4ff),
    onPrimaryContainer: Color(0xff001c38),
    secondary: Color(0xff77574d),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffffdbd1),
    onSecondaryContainer: Color(0xff2c150f),
    tertiary: Color(0xff6c5677),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xfff5d9ff),
    onTertiaryContainer: Color(0xff261431),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff410002),
    background: Color(0xfffdfcff),
    onBackground: Color(0xff1a1c1e),
    surface: Color(0xfffdfcff),
    onSurface: Color(0xff1a1c1e),
    surfaceVariant: Color(0xffdfe2eb),
    onSurfaceVariant: Color(0xff43474e),
    outline: Color(0xff73777f),
    outlineVariant: Color(0xffc3c6cf),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2f3033),
    onInverseSurface: Color(0xfff1f0f4),
    inversePrimary: Color(0xffa2c9ff),
    surfaceTint: Color(0xff1460a5),
  );

  static const ColorScheme flexSchemeDark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xffffaeda),
    onPrimary: Color(0xff610047),
    primaryContainer: Color(0xff7f1e60),
    onPrimaryContainer: Color(0xffffd8ea),
    secondary: Color(0xffb3cad4),
    onSecondary: Color(0xff1d333b),
    secondaryContainer: Color(0xff344a52),
    onSecondaryContainer: Color(0xffcee6f0),
    tertiary: Color(0xfff3ba9c),
    onTertiary: Color(0xff4a2713),
    tertiaryContainer: Color(0xff653d27),
    onTertiaryContainer: Color(0xffffdbca),
    error: Color(0xffffb4ab),
    onError: Color(0xff690005),
    errorContainer: Color(0xff93000a),
    onErrorContainer: Color(0xffffb4ab),
    background: Color(0xff1f1a1c),
    onBackground: Color(0xffeae0e3),
    surface: Color(0xff1f1a1c),
    onSurface: Color(0xffeae0e3),
    surfaceVariant: Color(0xff504349),
    onSurfaceVariant: Color(0xffd3c2c9),
    outline: Color(0xff9c8d93),
    outlineVariant: Color(0xff504349),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xffeae0e3),
    onInverseSurface: Color(0xff352f31),
    inversePrimary: Color(0xff9c3879),
    surfaceTint: Color(0xffffaeda),
  );
}
