name: "Build and Deploy Apps"

on:
  workflow_dispatch:

jobs:

  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Get last commit description
        id: commit
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "message<<EOF" >> $HOME/commit.txt
          echo "$COMMIT_MESSAGE" >> $HOME/commit.txt
          echo "EOF" >> $HOME/commit.txt
  
      - name: Extract version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //')
          echo "version=${VERSION}" >> $HOME/version.txt
  
      - name: Update appcast.xml
        run: |
          APPCAST_PATH="appcast.xml"
          VERSION=$(cat $HOME/version.txt)
          DESCRIPTION=$(cat $HOME/commit.txt)
          PUBDATE=$(date -u +"%a, %d %b %Y %H:%M:%S %z")
  
          # Update Android entry in appcast.xml
          sed -i "/<item>/,/<\/item>/ { /<title>Version/ s/<title>Version .*<\/title>/<title>Version ${VERSION}<\/title>/; /<description>/ s/<description>.*<\/description>/<description>${DESCRIPTION}<\/description>/; /<pubDate>/ s/<pubDate>.*<\/pubDate>/<pubDate>${PUBDATE}<\/pubDate>/; /<enclosure/ s/sparkle:version=\".*\"/sparkle:version=\"${VERSION}\"/ }" $APPCAST_PATH
  
          # Update iOS entry in appcast.xml
          sed -i "/<item>/,/<\/item>/ { /sparkle:os=\"ios\"/ { /<title>Version/ s/<title>Version .*<\/title>/<title>Version ${VERSION}<\/title>/; /<description>/ s/<description>.*<\/description>/<description>${DESCRIPTION}<\/description>/; /<pubDate>/ s/<pubDate>.*<\/pubDate>/<pubDate>${PUBDATE}<\/pubDate>/; /<enclosure/ s/sparkle:version=\".*\"/sparkle:version=\"${VERSION}\"/ } }" $APPCAST_PATH
  
          # Commit and push changes
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $APPCAST_PATH
          git commit -m "${DESCRIPTION}"
          git push
