name: "Build and Deploy Apps"

on:
  workflow_dispatch:

jobs:
  update_pubspec_and_appcast: 
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get last commit description
        id: commit
        run: |
            COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            echo "message<<EOF" >> $GITHUB_ENV
            echo "$COMMIT_MESSAGE" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
      - name: Extract version from pubspec.yaml
        id: version
        run: |
            # Extract the current version
            VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //')
            # Extract the build number
            BUILD_NUMBER=$(echo $VERSION | cut -d'+' -f2)
            # Increment the build number
            NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
            # Update the version with the new build number
            NEW_VERSION_WITHOUT_BUILD=$(echo $VERSION | cut -d'+' -f1)
            NEW_VERSION=${NEW_VERSION_WITHOUT_BUILD}"+$NEW_BUILD_NUMBER"
            echo "versionWithoutBuild=${NEW_VERSION_WITHOUT_BUILD}" >> $GITHUB_ENV
            echo "buildNumber=${NEW_BUILD_NUMBER}" >> $GITHUB_ENV
            echo "version=${NEW_VERSION} >> $GITHUB_ENV
            # Update the version in the pubspec.yaml
            sed -i "s/version: $VERSION/version: $NEW_VERSION/" pubspec.yaml
            # Commit the changes
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add pubspec.yaml
          

      - name: Update appcast.xml
        run: |
            PUBDATE=$(date -u +"%a, %d %b %Y %H:%M:%S %z")
            # Update Android entry in appcast.xml
            sed -i "  
            s|<title>Version .*<\/title>|<title>Version ${{ env.version }}<\/title>|g;  
            s|<description>.*<\/description>|<description>${{ env.version }}: ${{ env.message }}<\/description>|g;  
            s|<pubDate>.*<\/pubDate>|<pubDate>${PUBDATE}<\/pubDate>|g;  
            s|sparkle:version=\"[^\"]*\"|sparkle:version=\"${{ env.buildNumber }}\"|g;  
            s|sparkle:shortVersionString=\"[^\"]*\"|sparkle:shortVersionString=\"${{ env.versionWithoutBuild }}\"|g;  
            " appcast.xml  
            git add appcast.xml
            git commit -m "${{ env.version}}: ${{ env.message }}"
            git push

  build_ios:
    runs-on: macos-latest
    needs: update_pubspec_and_appcast
    steps:
      - name: Check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: touch .env && echo "RIOT_API_KEY=${{ secrets.RIOT_API_KEY }}" >> .env && flutter build ipa --release --export-options-plist=ios/GithubActionsExportOptions.plist
          certificate-base64: ${{ secrets.APPLE_SIGNING_CERTIFICATE }}
          certificate-password: ${{ secrets.APPLE_SIGNING_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
          keychain-password: ${{ secrets.APPLE_SIGNING_PASSWORD }}

      - name: Print contents of build folder
        run: |
          echo "Contents of the build folder:"
          ls -R build/ios

      - name: "Upload app to TestFlight"
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: "/Users/runner/work/valoralysis/valoralysis/build/ios/ipa/valoralysis.ipa"
          issuer-id: ${{ secrets.APP_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

  build_android:
    runs-on: ubuntu-latest
    needs: update_pubspec_and_appcast
    env:
      JAVA_VERSION: 17.0
      FLUTTER_VERSION: 3.19.0
      AAB_PATH: build/app/outputs/bundle/release/app-release.aab
      KEYSTORE_PATH: android/keystore_valoralysis.jks
      KEY_PROPS_PATH: android/key.properties
      SERVICE_ACCOUNT_PATH: store_credentials.json
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Java to compile the Android project
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Decode Android keystore
        run: echo "${{ secrets.ANDROID_KEY }}" | base64 --decode > ${{ env.KEYSTORE_PATH }}

      - name: Decode Android key properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > ${{ env.KEY_PROPS_PATH }}

      - name: Decode Android Service Account
        run: echo "${{ secrets.ANDROID_SERVICE_ACCOUNT }}" | base64 --decode > ${{ env.SERVICE_ACCOUNT_PATH }}

      - name: create .env
        run: touch .env && echo "RIOT_API_KEY=${{ secrets.RIOT_API_KEY }}" >> .env

      - name: Run flutter pub get
        run: flutter pub get

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: Build aab
        run: flutter build appbundle --release --dart-define=RIOT_API_KEY=${{ secrets.RIOT_API_KEY }}

      - name: Sign Android App Bundle
        run: jarsigner -keystore ${{ env.KEYSTORE_PATH }} -storepass ${{ secrets.ANDROID_KEY_PASSWORD }} -keypass ${{ secrets.ANDROID_KEY_PASSWORD }} -sigalg SHA256withRSA -digestalg SHA-256 -signedjar build/app/outputs/bundle/release/app-release-signed.aab build/app/outputs/bundle/release/*.aab Valoralysis

      - name: Deploy to Play Store (Internal testing)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.melsayed.valoralysis
          status: draft
          releaseFiles: build/app/outputs/bundle/release/app-release-signed.aab
          track: internal
          
  revert_changes:
    runs-on: ubuntu-latest
    needs: [build_ios, build_android]
    if: ${{ failure() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Revert last commit
        run: |
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git reset --hard HEAD^
        
  notify:
    runs-on: ubuntu-latest
    needs: [build_ios, build_android]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Get last commit description
        id: commit
        run: |
            COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            echo "message<<EOF" >> $GITHUB_ENV
            echo "$COMMIT_MESSAGE" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: ${{ env.message }}
